### PR TITLE
Comment most of SymbolicObj3 back in.

### PR DESCRIPTION
**Pull request by jbj**
3D rendering seems to have been buggy since April, between versions 0.0.1 and 0.0.2. Objects with sharp edges, such as cubes and cylinders, get rendered with those edges "crinkled". You can see this by rendering the sample code of the first 3D object in README.md with the latest version of ImplicitCAD. It looks much uglier than the picture in the readme.

I bisected this to have happened in commit 14af9390, where most of the SymbolicObj3.hs was commented out. This seems to have disabled symbolic object rendering, so everything is done with marching cubes.

I don't know if this is the right fix, but at least this makes  the examples from the readme pretty again. I haven't tested whether all the code that gets revived here actually works, but at least it compiles without problems.

### CODE REVIEW

**Comment by silky** [comment]
any updated thoughts on this?

to answer @ksjogo ; the `SaneOperators` class has been removed and they've moved to `Data.VectorSapce` where the "S.+" operator is now the `^+^` operator from that library

see this commit - https://github.com/colah/ImplicitCAD/commit/b5aaaed5dac50760469785ad06b18e550296560a

**Comment by mmachenry** [comment]
This has compile-time errors.

Graphics/Implicit/Export/SymbolicObj3.hs:35:25: Not in scope: ‘S.+’

See @silky's comment above. I can't just merge it like this. Also it's trying to merge against a rather old version of the file that used to have tabs so it has a huge amount of conflicts. Basically every line in the file.

**Comment by silky** [comment]
before i commented i actually got (essentially) this working, but it didn't result in any noticable difference

i also note that in general STL generation from ImplicitCAD is very slow. for the logo from - https://github.com/silky/haskmas - it takes about 2 minutes for ImplicitCAD to generate the stl, whereas outputing `scad` code for, say, OpenSCAD to process and letting that general the STL (which takes 5 seconds or so) is much more efficient

and furthermore, even the STL that ImplicitCAD generates isn't particularly "nice"; it has several artefacts (i.e. big zero-height sheets between segments, etc). 

so i think something a bit more substantial is required ... (that said, ImplicitCAD -> .scad is a nice process.)

**Comment by julialongtin** [comment]
Can i get you to try the newest version of ImplicitCAD?

Julia Longtin

**Comment by Cookshak** [comment]
Will do, and I'll add a license comment for the new license too.


On Dec 4, 2016 10:14 AM, "Julia Longtin" <notifications@github.com> wrote:

Can i get you to try the newest version of ImplicitCAD?

Julia Longtin

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/colah/ImplicitCAD/pull/67#issuecomment-264716672>, or mute
the thread

**Comment by Cookshak** [comment]
Apologies, I just realized this was not directed at me.

On Dec 4, 2016 11:06 AM, "Kelvin Cookshaw" <kelvin@cookshaw.com> wrote:

Will do, and I'll add a license comment for the new license too.


On Dec 4, 2016 10:14 AM, "Julia Longtin" <notifications@github.com> wrote:

Can i get you to try the newest version of ImplicitCAD?

Julia Longtin

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/colah/ImplicitCAD/pull/67#issuecomment-264716672>, or mute
the thread

**Comment by julialongtin** [comment]
I'm closing this, as it's old, and good results can be generated by matching the resolution with the layer height of your 3d print. selectable graineyness for the win.
